apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-chart.fullname" . }}-config
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "keyCloakUrl": "{{ .Values.config.keyCloakUrl }}",
      "apiUrl": "{{ .Values.config.apiUrl }}",
      "filesUrl": "{{ .Values.config.filesUrl }}",
      "production": true
    }