apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
spec:
  replicas: {{ .Values.frontend.deployment.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.deployment.image.repository }}:{{ .Values.frontend.deployment.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.deployment.image.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.serviceName }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: frontend